spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacodb
    password: tacopassword
    driver-class-name: com.mysql.jdbc.Driver
    schema: schema.sql
    data: data.sql

server:
  port: 8443
  ssl:
    key-store: C:\Users\xiagu\mykeys.jks
    key-store-password: letmein
    key-password: letmein

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
  file:
    path: /logs/TacoCloud.log

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url:
#      jdbc: h2:mem:testdb
#url:jdbc:h2:mem:testdb

#server:
#  port: 0

